/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.mavendb;

import br.edu.ifsp.mavendb.TO.TOCity;
import javax.swing.JOptionPane;

/**
 *
 * @author ht3010902
 */
public class LP3PopulationLocator extends javax.swing.JFrame {

    /**
     * Creates new form LP3PopulationLocator
     */
     DAOUser daouser = new DAOUser();
     TOCity city = new TOCity();
    public LP3PopulationLocator() {
        initComponents();
    }
   
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_inCidade = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtf_nomeCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jlb_Cidade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_PopCidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jb_desconectar = new javax.swing.JButton();
        jb_addTitulo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Procure a cidade mais populosa de um país:");

        jLabel2.setText("Digite o código da cidade:");

        jtf_inCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_inCidadeActionPerformed(evt);
            }
        });

        jb_buscar.setText("Buscar");
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("A cidade com maior população do país selecionado é:");

        jtf_nomeCidade.setEditable(false);
        jtf_nomeCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomeCidadeActionPerformed(evt);
            }
        });

        jLabel4.setText("A população de");

        jlb_Cidade.setForeground(new java.awt.Color(255, 51, 0));

        jLabel6.setText("é igual a:");

        jtf_PopCidade.setEditable(false);

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jb_desconectar.setText("Desconectar");
        jb_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_desconectarActionPerformed(evt);
            }
        });

        jb_addTitulo.setText("Adicionar");
        jb_addTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_addTituloActionPerformed(evt);
            }
        });

        jLabel5.setText("Deseja adicionar ! ao nome da cidade?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_desconectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlb_Cidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_PopCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jb_addTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_nomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_buscar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_inCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_inCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_buscar)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_nomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlb_Cidade)
                    .addComponent(jLabel6)
                    .addComponent(jtf_PopCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jb_desconectar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_addTitulo)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_inCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_inCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_inCidadeActionPerformed

    private void jtf_nomeCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomeCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomeCidadeActionPerformed

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        daouser.connect();
        
        city = daouser.topOnePop(jtf_inCidade.getText());
        jlb_Cidade.setText(city.getNome());
        jtf_nomeCidade.setText(city.getNome());
        jtf_PopCidade.setText(city.getPopulation() + "");
        
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtf_inCidade.setText("");
        jtf_nomeCidade.setText("");
        jtf_PopCidade.setText("");
        jlb_Cidade.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_desconectarActionPerformed
        daouser.disconnect();
        JOptionPane.showMessageDialog(rootPane, "Desconectado com sucesso!!");
        jtf_inCidade.setText("");
        jtf_nomeCidade.setText("");
        jtf_PopCidade.setText("");
        dispose();
    }//GEN-LAST:event_jb_desconectarActionPerformed

    private void jb_addTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_addTituloActionPerformed
        daouser.updateChar(jtf_nomeCidade.getText());
        jtf_inCidade.setText("");
        jtf_nomeCidade.setText("");
        jtf_PopCidade.setText("");
    }//GEN-LAST:event_jb_addTituloActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jb_addTitulo;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_desconectar;
    public javax.swing.JLabel jlb_Cidade;
    public javax.swing.JTextField jtf_PopCidade;
    public javax.swing.JTextField jtf_inCidade;
    public javax.swing.JTextField jtf_nomeCidade;
    // End of variables declaration//GEN-END:variables
}
